server:
  port: 8081
spring:
  datasource:
    url: ${MAIN_DB_URL}
    username: ${MAIN_DB_ID}
    password: ${MAIN_DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  com:
    amazonaws:
      util:
        EC2MetadataUtils: error
  org:
    hibernate:
      type:
        descriptor:
          sql:
            org.hibernate.type.descriptor.sql.BasicBinder: trace
    springframework:
      web.servlet: debug